[package]
name = "diffus-derive-test"
version = "0.1.0"
authors = ["Jim Holmström <jim.holmstroem@gmail.com>"]
edition = "2018"


[dependencies]
diffus = { path = "../diffus" }
diffus-derive = { path = "../diffus-derive" }
