[package]
name = "diffus"
version = "0.1.0"
authors = ["Jim Holmström <jim.holmstroem@gmail.com>"]
edition = "2018"


[dependencies]

[dependencies.difference]
version = "2.0"
optional = true

[dependencies.indexmap]
version = "1"
optional = true

[dependencies.lcs]
version = "0.2"
optional = true

[features]
default = [ "vec-impl", "string-impl" ]

string-impl = [ "difference" ]
vec-impl = [ "lcs" ]
indexmap-impl = [ "indexmap" ]
