[package]
name = "diffus-derive"
version = "0.1.0"
authors = ["Jim Holmström <jim.holmstroem@gmail.com>"]
edition = "2018"

[dependencies]
syn = "1.0"
quote = "1.0"
proc-macro2 = "1.0"

diffus = { path = ".." }

[lib]
proc-macro = true
